create table phpbb_forums
(
    forum_id                 INTEGER
        primary key autoincrement,
    parent_id                INTEGER UNSIGNED     default '0'  not null,
    left_id                  INTEGER UNSIGNED     default '0'  not null,
    right_id                 INTEGER UNSIGNED     default '0'  not null,
    forum_parents            MEDIUMTEXT(16777215) default ''   not null,
    forum_name               TEXT(65535)          default ''   not null,
    forum_desc               TEXT(65535)          default ''   not null,
    forum_desc_bitfield      VARCHAR(255)         default ''   not null,
    forum_desc_options       INTEGER UNSIGNED     default '7'  not null,
    forum_desc_uid           VARCHAR(8)           default ''   not null,
    forum_link               VARCHAR(255)         default ''   not null,
    forum_password           VARCHAR(255)         default ''   not null,
    forum_style              INTEGER UNSIGNED     default '0'  not null,
    forum_image              VARCHAR(255)         default ''   not null,
    forum_rules              TEXT(65535)          default ''   not null,
    forum_rules_link         VARCHAR(255)         default ''   not null,
    forum_rules_bitfield     VARCHAR(255)         default ''   not null,
    forum_rules_options      INTEGER UNSIGNED     default '7'  not null,
    forum_rules_uid          VARCHAR(8)           default ''   not null,
    forum_topics_per_page    INTEGER UNSIGNED     default '0'  not null,
    forum_type               TINYINT(4)           default '0'  not null,
    forum_status             TINYINT(4)           default '0'  not null,
    forum_last_post_id       INTEGER UNSIGNED     default '0'  not null,
    forum_last_poster_id     INTEGER UNSIGNED     default '0'  not null,
    forum_last_post_subject  TEXT(65535)          default ''   not null,
    forum_last_post_time     INTEGER UNSIGNED     default '0'  not null,
    forum_last_poster_name   VARCHAR(255)         default ''   not null,
    forum_last_poster_colour VARCHAR(6)           default ''   not null,
    forum_flags              TINYINT(4)           default '32' not null,
    display_on_index         INTEGER UNSIGNED     default '1'  not null,
    enable_indexing          INTEGER UNSIGNED     default '1'  not null,
    enable_icons             INTEGER UNSIGNED     default '1'  not null,
    enable_prune             INTEGER UNSIGNED     default '0'  not null,
    prune_next               INTEGER UNSIGNED     default '0'  not null,
    prune_days               INTEGER UNSIGNED     default '0'  not null,
    prune_viewed             INTEGER UNSIGNED     default '0'  not null,
    prune_freq               INTEGER UNSIGNED     default '0'  not null,
    display_subforum_list    INTEGER UNSIGNED     default '1'  not null,
    display_subforum_limit   INTEGER UNSIGNED     default '0'  not null,
    forum_options            INTEGER UNSIGNED     default '0'  not null,
    enable_shadow_prune      INTEGER UNSIGNED     default '0'  not null,
    prune_shadow_days        INTEGER UNSIGNED     default '7'  not null,
    prune_shadow_freq        INTEGER UNSIGNED     default '1'  not null,
    prune_shadow_next        INT(11)              default '0'  not null,
    forum_posts_approved     INTEGER UNSIGNED     default '0'  not null,
    forum_posts_unapproved   INTEGER UNSIGNED     default '0'  not null,
    forum_posts_softdeleted  INTEGER UNSIGNED     default '0'  not null,
    forum_topics_approved    INTEGER UNSIGNED     default '0'  not null,
    forum_topics_unapproved  INTEGER UNSIGNED     default '0'  not null,
    forum_topics_softdeleted INTEGER UNSIGNED     default '0'  not null
);

create index phpbb_forums_forum_lastpost_id
    on phpbb_forums (forum_last_post_id);

create index phpbb_forums_left_right_id
    on phpbb_forums (left_id, right_id);

INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (1, 0, 3, 4, '', 'Requests', '<t>Post requests for help, share your own projects, or seek collaborators on hacking-related tasks.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 0, 0, 1, 2, '', 1736014568, '4dm1n', 'AA0000', 32, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (3, 0, 1, 2, '', 'General Discussion', '<t>A catch-all area for conversations that don''t fit neatly into other categories.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (4, 0, 5, 6, '', 'Tools and Resources', '<t>Share and discuss various tools, software, and resources used in the field of cybersecurity.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (5, 0, 7, 8, '', 'Vulnerability Disclosure and Bug Bounty', '<t>Discuss vulnerabilities, report bugs, and share experiences from bug bounty programs.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (6, 0, 9, 10, '', 'Penetration Testing and Ethical Hacking', '<t>Share knowledge, techniques, and real-world examples of penetration testing, ethical hacking, and red teaming exercises.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (7, 0, 11, 12, '', 'Malware Analysis and Reverse Engineering', '<t>Analyze and dissect malware, viruses, and other malicious software, and discuss reverse engineering techniques.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (9, 0, 13, 14, '', 'Security News and Announcements', '<t>Share news about significant security breaches, updates from the industry, and announcements from organizations or companies.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (10, 0, 15, 16, '', 'Malware Development', '<t>Develop, test, and share your own malware, as well as discuss malware creation techniques, anti-malware evasion methods, and more.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (11, 0, 17, 18, '', 'Hacking Challenges and CTFs', '<t>Participate in Capture The Flag (CTF) challenges, discuss hacking challenges, and learn from others'' experiences.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (12, 0, 19, 20, '', 'Off-Topic Discussion', '<t>Discuss non-hacking related topics, such as books, movies, or personal interests (optional).</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (13, 0, 21, 22, '', 'The Life', '<t>Share stories, experiences, and advice on the life, including freelancing, working with clients, and more.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 0, 0, '', 0, '', '', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_forums (forum_id, parent_id, left_id, right_id, forum_parents, forum_name, forum_desc, forum_desc_bitfield, forum_desc_options, forum_desc_uid, forum_link, forum_password, forum_style, forum_image, forum_rules, forum_rules_link, forum_rules_bitfield, forum_rules_options, forum_rules_uid, forum_topics_per_page, forum_type, forum_status, forum_last_post_id, forum_last_poster_id, forum_last_post_subject, forum_last_post_time, forum_last_poster_name, forum_last_poster_colour, forum_flags, display_on_index, enable_indexing, enable_icons, enable_prune, prune_next, prune_days, prune_viewed, prune_freq, display_subforum_list, display_subforum_limit, forum_options, enable_shadow_prune, prune_shadow_days, prune_shadow_freq, prune_shadow_next, forum_posts_approved, forum_posts_unapproved, forum_posts_softdeleted, forum_topics_approved, forum_topics_unapproved, forum_topics_softdeleted) VALUES (14, 0, 23, 24, '', 'Requests', '<t>Post requests for help, share your own projects, or seek collaborators on hacking-related tasks.</t>', '', 7, '', '', '', 0, '', '', '', '', 7, '', 0, 1, 0, 9, 63, 'Re: Seeking Assistance with a Disruptive Individual', 1736080282, 'Zephyr', '00AA00', 48, 1, 1, 1, 0, 0, 7, 7, 1, 1, 0, 0, 0, 7, 1, 0, 5, 0, 0, 1, 0, 0);
