version: '3.3'

services:
  challenge-saas-platform:
    build: saas-platform
    image: scl-challenge-jump-around-saas-platform  # name of the built image
    container_name: scl-challenge-saas-platform
    stop_grace_period: 0s
    networks:
      playground-net:
        ipv4_address: 172.20.0.45

  challenge-proxy-hop:
    build: proxy-hop
    image: scl-challenge-jump-around-proxy-hop  # name of the built image
    container_name: scl-challenge-proxy-hop
    stop_grace_period: 0s
    networks:
      playground-net:
        ipv4_address: 172.20.0.47

  challenge-victim:
    build: victim
    image: scl-challenge-jump-around-victim  # name of the built image
    container_name: scl-challenge-victim
    stop_grace_period: 0s
    networks:
      playground-net:
        ipv4_address: 172.20.0.49

networks:
  playground-net:
    external: true
