services:
  hackerlab:
    build: ./hackerlab
    container_name: hackerlab
    hostname: hackerlab
    restart: always
    ports:
      - "2222:22"
    networks:
      playground-net:
        ipv4_address: 172.20.0.2

  dashboard:
    build: ./dashboard
    container_name: dashboard
    hostname: dashboard
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      playground-net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./classes:/classes
      - ./challenges:/challenges
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "python", "-c", "'import requests; response = requests.get(\"http://localhost:80/\"); assert response.status_code == 200'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      playground-net:
        ipv4_address: 172.20.0.100
    healthcheck:
      test: ollama --version || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  playground-net:
    name: "playground-net"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
