services:
  hackerlab:
    build: ./hackerlab
    container_name: scl-hackerlab
    hostname: hackerlab
    restart: on-failure
    volumes:
      - ./hackerlab/data:/data
    ports:
      - "127.0.0.1:2222:22"
    networks:
      playground-net:
        ipv4_address: 172.20.0.2

  dashboard:
    build: ./dashboard
    container_name: scl-dashboard
    hostname: dashboard
    restart: on-failure
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    networks:
      playground-net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./classes:/classes
      - ./challenges:/challenges
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "python", "-c", "'import requests; response = requests.get(\"http://localhost:80/\"); assert response.status_code == 200'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ollama:
    image: ollama/ollama
    container_name: scl-ollama
    volumes:
      - ./ollama:/root/.ollama
    restart: on-failure
    networks:
      playground-net:
        ipv4_address: 172.20.0.100
    healthcheck:
      test: ollama --version || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  playground-net:
    name: "playground-net"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
