version: '3.7'
services:
  class-11-lab:
    build: .
    image: scl-class-11-lab  # name of the built image
    container_name: scl-class-11-lab
    hostname: class-11-lab
    stop_grace_period: 0s
    platform: linux/amd64 # important
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 8g
    stdin_open: true
    networks:
      playground-net:
        ipv4_address: 172.20.0.101

networks:
  playground-net:
    external: true
