version: '3.3'

services:
  # Routing between on-prem and auxiliary network(s)
  off-prem-router1:
    build: off-prem-router1
    image: scl-campaign-miro-cr-off-prem-router1  # name of the built image
    container_name: scl-campaign-miro-cr-off-prem-router1
    stop_grace_period: 0s
    networks:
      cr-dc1:
        ipv4_address: 10.2.0.2
      cr-aux:
        ipv4_address: 10.3.0.2
      cr-cn1:
        ipv4_address: 10.0.0.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
  # Auxiliary camera connected to auxiliary network + "internet"
  camera:
    build: camera
    image: scl-campaign-miro-cr-camera  # name of the built image
    container_name: scl-campaign-miro-cr-camera
    stop_grace_period: 0s
    networks:
      cr-aux:
        ipv4_address: 10.3.0.211
      playground-net:
        ipv4_address: 172.20.0.231
  # generic user machine
  user-machine:
    build: user-machine
    image: scl-campaign-miro-cr-user-machine  # name of the built image
    container_name: scl-campaign-miro-cr-user-machine
    stop_grace_period: 0s
    networks:
      cr-cn1:
        ipv4_address: 10.0.0.6
    cap_add:
      - NET_ADMIN
      - NET_RAW
  # Location (1) Proxy
  locproxy:
    build: locproxy
    image: scl-campaign-miro-cr-locproxy  # name of the built image
    container_name: scl-campaign-miro-cr-locproxy
    stop_grace_period: 0s
    networks:
      cr-cn1:
        ipv4_address: 10.0.0.5
        aliases:
          - locproxy
    cap_add:
      - NET_ADMIN
      - NET_RAW
  # Router from CN1 to the outside world
  public-facing-router2:
    build: public-facing-router2
    image: scl-campaign-miro-cr-public-facing-router2  # name of the built image
    container_name: scl-campaign-miro-cr-public-facing-router2
    stop_grace_period: 0s
    networks:
      cr-cn1:
        ipv4_address: 10.0.0.4
        aliases:
          - public-facing-router2
      playground-net:
        # same as the flag to knock-knock/whos-there
        ipv4_address: 172.20.0.239
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
  # Employee record system
  record-system:
    build: record-system
    image: scl-campaign-miro-cr-record-system
    container_name: scl-campaign-miro-cr-record-system
    stop_grace_period: 0s
    networks:
      cr-cn1:
        ipv4_address: 10.0.0.8
  # these have been used just to create logs and do not have to be (probably should not be) present when solving the challenge:
#  murray-pc:
#    container_name: scl-cr-murray-pc
#    stop_grace_period: 0s
#    build: user-machine
#    networks:
#      cr-cn1:
#        ipv4_address: 10.0.1.233
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
#  murray-phone:
#    container_name: scl-cr-murray-phone
#    stop_grace_period: 0s
#    build: user-machine
#    networks:
#      cr-cn1:
#        ipv4_address: 10.0.4.18
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW

# ALL GATEWAYS are just specified here to make sure they have static IPs, we are NOT using them at all
networks:
  # auxiliary devices outside the main network
  cr-aux:
    ipam:
      config:
        - subnet: 10.3.0.0/24
          gateway: 10.3.0.1
  # company network 1 = location 1
  cr-cn1:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
  # company datacenter 1
  cr-dc1:
    ipam:
      config:
        - subnet: 10.2.0.0/20
          gateway: 10.2.0.1
  # "internet"
  playground-net:
    external: true
